name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        elixir: ['1.14.5', '1.15.7', '1.16.0']
        otp: ['25.3', '26.2']
        exclude:
          - elixir: '1.16.0'
            otp: '25.3'

    steps:
    - uses: actions/checkout@v4
    
    - name: Install GUI and OpenGL dependencies
      run: |
        sudo apt-get update
        
        # Install wxWidgets 3.2 packages (Ubuntu 24.04 has 3.2, not 3.0)
        sudo apt-get install -y \
          libwxgtk3.2-1t64 \
          libwxgtk3.2-dev \
          libwxgtk-gl3.2-1t64 \
          libwxgtk-media3.2-1t64 \
          libwxgtk-media3.2-dev \
          libwxgtk-webview3.2-1t64 \
          libwxgtk-webview3.2-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          mesa-common-dev \
          xvfb \
          x11-utils \
          libx11-dev \
          libxrandr2 \
          libxi6 \
          libxcursor1 \
          libxinerama1 \
          libgtk-3-dev \
          libglib2.0-dev
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
        
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-
          ${{ runner.os }}-mix-
          
    - name: Install dependencies
      run: mix deps.get
      
    - name: Compile
      run: mix compile --warnings-as-errors
      
    - name: Run tests with virtual display
      run: xvfb-run -a mix test --exclude interactive
      env:
        # Ensure software rendering is used
        LIBGL_ALWAYS_SOFTWARE: 1
        # Mark as CI environment
        CI: true
